spring:
  application:
    name: app-demo

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo
    username: demo_user
    password: demo_pass

# Flyway uses its own jdbc driver
  flyway:
    url: jdbc:postgresql://localhost:5432/demo
    user: demo_user
    password: demo_pass
    locations: classpath:db/migration
